### ISSUE TITLE
cloning repo and starting dev server won't start

### ISSUE THREAD

**Issue by brianyang** [reactGo/reactGo#359]
cloning the repo and running `npm run dev` throws an error
### Description
- Type: Question
- Related Issue: `#abc`

---
## Bug

**Expected Behavior**
run `$ npm run dev` to start the app

**Actual Behavior**
server won't start. Error - SyntaxError: Unexpected token import

```

❯ npm run dev                                                                                                                                      master

> react-webpack-node@1.7.16 dev /Users/b/Public/react-full/react-webpack-node
> cross-env NODE_ENV=development nodemon

[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: app/server.jsx app/routes.jsx app/helmconfig.js app/components/Meta.jsx /Users/b/Public/react-full/react-webpack-node/server/**/* /Users/b/Public/react-full/react-webpack-node/webpack/**/*
[nodemon] starting `npm run build:dev && npm run babel-node -- server/index.js`

> react-webpack-node@1.7.16 build:dev /Users/b/Public/react-full/react-webpack-node
> cross-env NODE_ENV=development webpack --colors --config ./webpack/webpack.config.dev-server.js

Hash: 121bb10da7cafc608c08
Version: webpack 1.13.1
Time: 3422ms
    Asset     Size  Chunks             Chunk Names
server.js  1.22 MB       0  [emitted]  server
    + 364 hidden modules

> react-webpack-node@1.7.16 babel-node /Users/b/Public/react-full/react-webpack-node
> babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index.js"

/Users/b/Public/react-full/react-webpack-node/server/index.js:1
(function (exports, require, module, __filename, __dirname) { import express from 'express';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/b/Public/react-full/react-webpack-node/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at /Users/b/Public/react-full/react-webpack-node/node_modules/babel-cli/lib/_babel-node.js:160:24
    at Object.<anonymous> (/Users/b/Public/react-full/react-webpack-node/node_modules/babel-cli/lib/_babel-node.js:161:7)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "run" "babel-node" "--" "server/index.js"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! react-webpack-node@1.7.16 babel-node: `babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-webpack-node@1.7.16 babel-node script 'babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-webpack-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node --presets es2015,stage-0 --ignore node_modules,public "server/index.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-webpack-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-webpack-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/b/Public/react-full/react-webpack-node/npm-debug.log
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by brianyang** [comment]
babel-loader is expected globally. 

`npm i -g babel-loader`

**Comment by caranicas** [comment]
hi @brianyang I just tried this as well and didn't have any issues. What version of node are you using? `node -v` in your terminal to find out. I think you need a minimum of version 5 for this project to run. I am personally on on 6.2.0

**Comment by slavab89** [comment]
We're cleaning up issues on the project and since this is an old issue without updates we're closing it.
If you still experience this or have an issue, please comment here or open a new one
