### ISSUE TITLE
Repo's dev server is broken if you disable DB

### ISSUE THREAD

**Issue by donpinkus** [reactGo/reactGo#564]
I cloned this repo, followed the very basic setup instructions, and its not working.  Exact steps & error below.  Two other people reproduced this.

Node version: v6.3.0
NPM version: 3.10.3

**Steps**
1. Clone repo
2. run `npm install`
3. Turn off database requirement. Open `appConfig.js` change Ln 13 from `defaultExport.DB_TYPE = process.env.DB_TYPE || DB_TYPES.MONGO;` to `defaultExport.DB_TYPE = process.env.DB_TYPE || DB_TYPES.NONE;`
4. npm run dev
5. go to localhost:3000, and get the error below.

**Error**

```
{ Error: Request failed with status code 404
    at createError (/Users/donaldpinkus/Desktop/reactGo-master/public/assets/server.js:1132:16)
    at settle (/Users/donaldpinkus/Desktop/reactGo-master/public/assets/server.js:1104:13)
    at IncomingMessage.handleStreamEnd (/Users/donaldpinkus/Desktop/reactGo-master/public/assets/server.js:1625:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:973:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  config:
   { transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.14.0' },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     baseURL: 'http://localhost:3000',
     method: 'get',
     url: 'http://localhost:3000/topic',
     data: undefined },
  response:
   { status: 404,
     statusText: 'Not Found',
     headers:
      { 'x-powered-by': 'Express',
        'content-type': 'text/plain; charset=utf-8',
        'content-length': '9',
        etag: 'W/"9-nR6tc+Z4+i9RpwqTOwvwFw"',
        date: 'Wed, 28 Sep 2016 23:06:59 GMT',
        connection: 'close' },
     config:
      { transformRequest: [Object],
        transformResponse: [Object],
        headers: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        baseURL: 'http://localhost:3000',
        method: 'get',
        url: 'http://localhost:3000/topic',
        data: undefined },
     request:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /topic HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.14.0\r\nHost: localhost:3000\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        method: 'GET',
        path: '/topic',
        _ended: true,
        parser: null,
        res: [Object] },
     data: 'Not Found' } }
{ Error: Request failed with status code 404
    at createError (/Users/donaldpinkus/Desktop/reactGo-master/public/assets/server.js:1132:16)
    at settle (/Users/donaldpinkus/Desktop/reactGo-master/public/assets/server.js:1104:13)
    at IncomingMessage.handleStreamEnd (/Users/donaldpinkus/Desktop/reactGo-master/public/assets/server.js:1625:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:973:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  config:
   { transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.14.0' },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     baseURL: 'http://localhost:3000',
     method: 'get',
     url: 'http://localhost:3000/topic',
     data: undefined },
  response:
   { status: 404,
     statusText: 'Not Found',
     headers:
      { 'x-powered-by': 'Express',
        'content-type': 'text/plain; charset=utf-8',
        'content-length': '9',
        etag: 'W/"9-nR6tc+Z4+i9RpwqTOwvwFw"',
        date: 'Wed, 28 Sep 2016 23:06:59 GMT',
        connection: 'close' },
     config:
      { transformRequest: [Object],
        transformResponse: [Object],
        headers: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        baseURL: 'http://localhost:3000',
        method: 'get',
        url: 'http://localhost:3000/topic',
        data: undefined },
     request:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /topic HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.14.0\r\nHost: localhost:3000\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        method: 'GET',
        path: '/topic',
        _ended: true,
        parser: null,
        res: [Object] },
     data: 'Not Found' } }
```

**Comment by ZeroCho** [comment]
@donpinkus you need to remove **server/config/routes.js** 's controller part, I guess.

**Comment by ZeroCho** [comment]
related to #600
