### ISSUE TITLE
DB_TYPE = NONE, and npm run dev doesn't work

### ISSUE THREAD

**Issue by rstudner** [reactGo/reactGo#609]
On OSX

```
webpack built 22d9ed04381ce4a9482b in 3535ms
{ Error: Request failed with status code 404
    at createError (/Users/rstudner/git/reactGo/public/assets/server.js:1132:16)
    at settle (/Users/rstudner/git/reactGo/public/assets/server.js:1104:13)
    at IncomingMessage.handleStreamEnd (/Users/rstudner/git/reactGo/public/assets/server.js:1625:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  config:
   { transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.14.0' },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     baseURL: 'http://localhost:3000',
     method: 'get',
     url: 'http://localhost:3000/topic',
     data: undefined },
  response:
   { status: 404,
     statusText: 'Not Found',
     headers:
      { 'x-powered-by': 'Express',
        'content-type': 'text/plain; charset=utf-8',
        'content-length': '9',
        etag: 'W/"9-nR6tc+Z4+i9RpwqTOwvwFw"',
        date: 'Mon, 17 Oct 2016 11:49:01 GMT',
        connection: 'close' },
     config:
      { transformRequest: [Object],
        transformResponse: [Object],
        headers: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        baseURL: 'http://localhost:3000',
        method: 'get',
        url: 'http://localhost:3000/topic',
        data: undefined },
     request:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /topic HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.14.0\r\nHost: localhost:3000\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        method: 'GET',
        path: '/topic',
        _ended: true,
        parser: null,
        res: [Object] },
     data: 'Not Found' } }
(node:9685) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Converting circular structure to JSON
```

**Comment by StefanWerW** [comment]
related to #564 and #600

**Comment by ZeroCho** [comment]
This project loads user and topic stuffs from DB. So it cannot work without DB currently.

**Comment by Cleanshooter** [comment]
This is resolved in the current release from my tests. Suggest closing this issue.
