### ISSUE TITLE
Using react-toolbox and/or bootstrap-css?

### ISSUE THREAD

**Issue by omidahourai** [reactGo/reactGo#791]
## Question

**How to integrate either [bootstrap-css](https://github.com/StevenIseki/bootstrap-css) or [react-toolbox](http://react-toolbox.com/)?** (Related Issue: #196)

Either would be useful for bootstrapping. Tried bootstrap-css and got the following error (dealing with SSR i think?) Not sure why its occurring: 
```

/Users/oahourai/Development/scrumples/src/node_modules/bootstrap-css/lib/normalize.css:8
html {
     ^
SyntaxError: Unexpected token {
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/oahourai/Development/scrumples/src/node_modules/bootstrap-css/index.js:3:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

```

With react toolbox, it runs on SASS so I tried to implement with sass-loader in webpack, but got import errors:
```

ERROR in ../~/react-toolbox/lib/button/theme.scss
Module parse failed: /Users/oahourai/Development/scrumples/src/node_modules/react-toolbox/lib/button/theme.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (1:0)
    at Parser.pp$4.raise (/Users/oahourai/Development/scrumples/src/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/Users/oahourai/Development/scrumples/src/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/Users/oahourai/Development/scrumples/src/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/Users/oahourai/Development/scrumples/src/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/Users/oahourai/Development/scrumples/src/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/Users/oahourai/Development/scrumples/src/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/oahourai/Development/scrumples/src/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/oahourai/Development/scrumples/src/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/oahourai/Development/scrumples/src/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/oahourai/Development/scrumples/src/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/oahourai/Development/scrumples/src/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/oahourai/Development/scrumples/src/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/oahourai/Development/scrumples/src/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 @ ../~/react-toolbox/lib/button/index.js 26:13-36

```

Not a pro with webpack, but has anyone implemented these with the given postcss / modules configuration?

**Comment by choonkending** [comment]
@ArdentKid Can you share your webpack config or a branch of where this is implemented?

Based on the error message, it seems that when webpack is compiling the files, when it gets to stylesheet, e.g. `normalize.css`, it does not know how to deal with those files because it has not been told what webpack `loader` to use.

Out of curiosity, why are you using bootstrap css?

**Comment by ArdentKid** [comment]
Sorry for the late response, I put this on hold to prioritize other parts of my project. Will post an update if I try to add react-toolbox back in. Wanted bootstrap css so I wouldn't have to roll my own grid system but finding out more about flexbox and will likely implement that instead.

**Comment by hankyum** [comment]
https://github.com/css-modules/css-modules-require-hook solve my issue with you @ArdentKid

**Comment by slavab89** [comment]
We're cleaning the project and closing issues. I'm closing this since it doesnt have a direct issue with the project.
If you've found a solution, it would be great to have it here.
If you still have any issue, please comment here or open a new one.

Each module has its own different integration as it seems, `react-flexbox-grid` changed their build making the integration a lot easier (without too much hassle)
