### ISSUE TITLE
Can't include Third-Party-Plugin with styles 

### ISSUE THREAD

**Issue by mavo11** [reactGo/reactGo#850]
### Description
- Type:  Question

---------------------------------------------------------------
## Bug

D:\Users\marvonge\Documents\sandbox\reactGo\node_modules\react-calendar-timeline\modules\lib\Timeline.css:1
(function (exports, require, module, __filename, __dirname) { .react-calendar-timeline * {
                                                              ^
SyntaxError: Unexpected token .
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Users\marvonge\Documents\sandbox\reactGo\node_modules\react-calendar-timeline\modules\lib\Timeline.js:19:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Users\marvonge\Documents\sandbox\reactGo\node_modules\react-calendar-timeline\modules\index.js:7:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[nodemon] app crashed - waiting for file changes before starting...

**Steps to Reproduce**

- clone reactGo
- include any third-party-plugin you want which has styles included 
Tested with react-calendar-timeline and react-visjs-timeline

-----------------------------------------------------------------

## Question

**How to solve this issue?**
Didn't change any webpack files.

**Comment by slavab89** [comment]
You might want to look at this https://github.com/namespace-ee/react-calendar-timeline/issues/72
Basically this happens with libraries that dont use css modules. Happened to me as well with react-select.
https://github.com/reactGo/reactGo/issues/833

**Comment by slavab89** [comment]
We're trying to clean up the project and close issues.
We havent heard back from you so i'll assume it was resolved.
In case you still have an issue, please comment here or open a new one.
