### ISSUE TITLE
Can't Run / Build

### ISSUE THREAD

**Issue by jrodl3r** [reactGo/reactGo#872]
On `npm run dev` w/ latest, this is what I'm getting:

```
> xxx@0.1.0 dev /Users/Admin/Sites/xxx
> cross-env NODE_ENV=development nodemon

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/Admin/Sites/xxx/app/utils/**/* app/routes.jsx /Users/Admin/Sites/xxx/server/**/* /Users/Admin/Sites/xxx/webpack/**/*
[nodemon] starting `npm run build:dev && node compiled/server.dev.js`

> xxx@0.1.0 build:dev /Users/Admin/Sites/xxx
> cross-env NODE_ENV=development npm run webpack -- --env.server


Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, prune, publish, rb,
    rebuild, repo, restart, root, run, run-script, s, se,
    search, set, shrinkwrap, star, stars, start, stop, t, team,
    test, tst, un, uninstall, unpublish, unstar, up, update, v,
    version, view, whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /Users/Admin/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@4.6.1 /usr/local/lib/node_modules/npm
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxx@0.1.0 build:dev: `cross-env NODE_ENV=development npm run webpack -- --env.server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xxx@0.1.0 build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Admin/.npm/_logs/2017-05-08T03_19_09_471Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...
```

Just trying to get it up and running, Thx ; )

**Comment by choonkending** [comment]
Interesting. Do you mind printing the `debug.log` so I can get a better idea of what's happening?

**Comment by GGAlanSmithee** [comment]
My guess is this is caused by not running `npm i` before `npm run build`, making webpack complain about missing `prop-types` package, which was added recently. Please try this @jrodl3r

**Comment by jrodl3r** [comment]
debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.11.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:dev' ]
2 info using npm@4.6.1
3 info using node@v5.11.0
4 verbose run-script [ 'prebuild:dev', 'build:dev', 'postbuild:dev' ]
5 info lifecycle react-webpack-node@3.4.1~prebuild:dev: react-webpack-node@3.4.1
6 silly lifecycle react-webpack-node@3.4.1~prebuild:dev: no script for prebuild:dev, continuing
7 info lifecycle react-webpack-node@3.4.1~build:dev: react-webpack-node@3.4.1
8 verbose lifecycle react-webpack-node@3.4.1~build:dev: unsafe-perm in lifecycle true
9 verbose lifecycle react-webpack-node@3.4.1~build:dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Admin/Downloads/_New/reactGo-master/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Admin/Downloads/_New/reactGo-master/node_modules/.bin:/opt/local/bin:/opt/local/sbin:/Users/Admin/.node/bin:/usr/local/bin:/Users/Admin/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
10 verbose lifecycle react-webpack-node@3.4.1~build:dev: CWD: /Users/Admin/Downloads/_New/reactGo-master
11 silly lifecycle react-webpack-node@3.4.1~build:dev: Args: [ '-c',
11 silly lifecycle   'cross-env NODE_ENV=development npm run webpack -- --env.server' ]
12 silly lifecycle react-webpack-node@3.4.1~build:dev: Returned: code: 1  signal: null
13 info lifecycle react-webpack-node@3.4.1~build:dev: Failed to exec build:dev script
14 verbose stack Error: react-webpack-node@3.4.1 build:dev: `cross-env NODE_ENV=development npm run webpack -- --env.server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid react-webpack-node@3.4.1
16 verbose cwd /Users/Admin/Downloads/_New/reactGo-master
17 verbose Darwin 15.6.0
18 verbose argv "/usr/local/Cellar/node/5.11.0/bin/node" "/usr/local/bin/npm" "run" "build:dev"
19 verbose node v5.11.0
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 1
23 error react-webpack-node@3.4.1 build:dev: `cross-env NODE_ENV=development npm run webpack -- --env.server`
23 error Exit status 1
24 error Failed at the react-webpack-node@3.4.1 build:dev script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by jrodl3r** [comment]
So... Weird. I couldn't successfully `npm run build` on this random machine until AFTER i did `npm run dev` - Not sure why, but it's working now. Closing this out. Thx ; )
