### ISSUE TITLE
AWS Deployment Problem

### ISSUE THREAD

**Issue by trda** [reactGo/reactGo#923]
Hello,

I have launched an ec2 instance on AWS. 
I defined port according to [AWS deployment guide](https://github.com/choonkending/reactGo/blob/aws-docs/docs/deployment/aws/linux-ec2.md)., installed node.js and tried to run `npm start` command. But I got the below error. 

Do you have any idea, why did I get this error.

/home/ubuntu/xxx/webpack/webpack.config.js:15
module.exports = (env = {}) => {
                      ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at requireConfig (/home/ubuntu/xxx/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/ubuntu/xxx/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)

## FULL OUTPUT

**$ ls**
app           config    node_modules   package-lock.json  Roadmap.md
app.json      docs      nodemon.json   Procfile           server
Changelog.md  LICENSE   npm-debug.log  public_theme       webpack
common        __MACOSX  package.json   README.md

~/xxx$ **npm build**
~/xxx$ **npm start**

 react-webpack-node@3.4.1 start /home/ubuntu/xxx
 npm run build && cross-env NODE_ENV=production node compiled/server.js

 react-webpack-node@3.4.1 build /home/ubuntu/xxx
 npm run clean && cross-env NODE_ENV=production npm run webpack -- --env.browser && NODE_ENV=production npm run webpack -- --env.server

 react-webpack-node@3.4.1 clean /home/ubuntu/xxx
 rimraf public && rimraf compiled

 react-webpack-node@3.4.1 webpack /home/ubuntu/xxx
 webpack --colors --display-error-details --config ./webpack/webpack.config.js "--env.browser"

/home/ubuntu/xxx/webpack/webpack.config.js:15
module.exports = (env = {}) => {
                      ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at requireConfig (/home/ubuntu/xxx/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/ubuntu/xxx/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)

npm ERR! Linux 4.4.0-1022-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "webpack" "--" "--env.browser"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! react-webpack-node@3.4.1 webpack: `webpack --colors --display-error-details --config ./webpack/webpack.config.js "--env.browser"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-webpack-node@3.4.1 webpack script 'webpack --colors --display-error-details --config ./webpack/webpack.config.js "--env.browser"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-webpack-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --colors --display-error-details --config ./webpack/webpack.config.js "--env.browser"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-webpack-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-webpack-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/xxx/npm-debug.log

npm ERR! Linux 4.4.0-1022-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! react-webpack-node@3.4.1 build: `npm run clean && cross-env NODE_ENV=production npm run webpack -- --env.browser && NODE_ENV=production npm run webpack -- --env.server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-webpack-node@3.4.1 build script 'npm run clean && cross-env NODE_ENV=production npm run webpack -- --env.browser && NODE_ENV=production npm run webpack -- --env.server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-webpack-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && cross-env NODE_ENV=production npm run webpack -- --env.browser && NODE_ENV=production npm run webpack -- --env.server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-webpack-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-webpack-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/xxx/npm-debug.log

npm ERR! Linux 4.4.0-1022-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! react-webpack-node@3.4.1 start: `npm run build && cross-env NODE_ENV=production node compiled/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-webpack-node@3.4.1 start script 'npm run build && cross-env NODE_ENV=production node compiled/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-webpack-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && cross-env NODE_ENV=production node compiled/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-webpack-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-webpack-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/xxx/npm-debug.log
~/xxx$

**Comment by trda** [comment]
I have solved the problem. I would like to share all commands here for those who will install it later.

1. Install nodejs
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
2. Install nodejs
sudo apt-get install -y nodejs
3. Open the folder which includes the PEM file and run a terminal in this folder.
4. Run the below code to copy local file to remote folder.
scp -i pilaty.pem /Users/Archive.zip ubuntu@ec2-xx-xx-xxx-xx.eu-central-1.compute.amazonaws.com:/home/ubuntu/XXX/
5. Install UNZIP
sudo apt-get install unzip
6. Unzip file
unzip Archive.zip
7. Remove Archive.zip file
rm Archive.zip 
8. If you open related port in the security group, now you can see your web site on the public link.
http://ec2-xx-xx-xxx-xx.eu-central-1.compute.amazonaws.com:3003/
9. Install NGINX
sudo apt-get install nginx
10. Delete default config file
sudo rm /etc/nginx/sites-enabled/default
11. Create a new one
sudo nano /etc/nginx/sites-available/node
12. Run the below code to activate
sudo ln -s /etc/nginx/sites-available/node /etc/nginx/sites-enabled/node
13. Install forever
sudo npm install forever -g
14. Start app to run forever
sudo forever start app.js
15. To see all forever task, run the below code
sudo forever list
16. To stop one of them, run the below code
sudo forever stop PID
17. Ngnix Restart
/etc/init.d/nginx restart


## Ngnix My Config File

server {
    listen 80;
    server_name abc.com;

    location / {
        proxy_set_header   X-Forwarded-For $remote_addr;
        proxy_set_header   Host $http_host;
        proxy_pass         "http://127.0.0.1:3003";
    }
}

server {
    listen 80;
    server_name xyc.com;

    location / {
        proxy_set_header   X-Forwarded-For $remote_addr;
        proxy_set_header   Host $http_host;
        proxy_pass         "http://127.0.0.1:3001";
    }
}


server {
  listen 80;
  server_name www.xyc.com;
  rewrite ^(.*) http://xyc.com$1 permanent;
}
